# Generated by Django 5.2.6 on 2026-01-11 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=1250)),
                ('minimum_bid', models.IntegerField()),
                ('auction_end_date', models.DateField()),
                ('item_image', models.ImageField(blank=True, help_text='Auction item photo', null=True, upload_to='item_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='title_idx'), models.Index(fields=['description'], name='description_idx'), models.Index(fields=['-created_at'], name='created_at_idx')],
            },
        ),
    ]
